version: '3.9'
services:
  postgres:
    image: postgres:14
    volumes:
      - "pg:/var/lib/postgresql/data"
    environment:
      - PGPASSWORD=${PG_PASSWORD}
  redis:
    image: redis:7.0.5-bullseye
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
    env_file:
      - ".env"
    volumes:
      - "media:/var/www/app/media/"
      - "static:/var/www/app/static/"
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "media:/var/www/app/media/"
      - "static:/var/www/app/static/"
    ports:
      - "80:80"
volumes:
  pg:
  media:
  static:
