# Generated by Django 4.1.2 on 2022-10-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exponents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.CharField(choices=[('true', 'Опубликовано'), ('false', 'Не опубликовано'), ('rejected', 'Отклонено')], max_length=128, verbose_name='Опубликовано'),
        ),
    ]
