# Generated by Django 4.1.2 on 2022-10-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exponents', '0002_alter_review_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.CharField(choices=[('true', 'Опубликовано'), ('false', 'Не опубликовано'), ('rejected', 'Отклонено')], max_length=128, verbose_name='Опубликовано')),
                ('rejected_comment', models.TextField(blank=True, verbose_name='Комментарий к отклонению')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('partner_link', models.URLField()),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('video', 'Видео')], max_length=8, verbose_name='Тип контента')),
                ('html', models.TextField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('import_substitution_shield', models.BooleanField(verbose_name='Шилд импортозамещения')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='ExponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.CharField(choices=[('true', 'Опубликовано'), ('false', 'Не опубликовано'), ('rejected', 'Отклонено')], max_length=128, verbose_name='Опубликовано')),
                ('rejected_comment', models.TextField(blank=True, verbose_name='Комментарий к отклонению')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exponents.exponentcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория экспонента',
                'verbose_name_plural': 'Категории экспонентов',
            },
        ),
    ]
