# Generated by Django 4.1.2 on 2022-10-23 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exponents', '0002_exponent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exponent',
            name='image',
            field=models.ImageField(default='test', upload_to='', verbose_name='Главное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exponentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exponents.exponentcategory', verbose_name='Родительская категория'),
        ),
    ]
