# Generated by Django 4.1.2 on 2022-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exponents', '0003_exponents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exponent',
            name='inn',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ИНН предприятия'),
        ),
    ]
